networks:
  default:
    driver: bridge
    name: roboshop
    #external: true
services:
  mongodb:
    image: bhargav9968/mongodb:v1
    container_name: mongodb  
  catalogue:
    image: bhargav9968/catalogue:v1
    container_name: catalogue
    depends_on: 
    - mongodb 
  redis:
    image: redis:7.0
    container_name: redis  
  user:
    image: bhargav9968/user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
   image: bhargav9968/cart:v1
   container_name: cart
   depends_on:
   - redis 
   - catalogue
  mysql:
     image: bhargav9968/mysql:v1
     container_name: mysql
  shipping:
    image: bhargav9968/shipping:v1
    container_name: shipping
    depends_on:
    - cart
    - mysql   
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
  payment:
    image: bhargav9968/payment:v1
    container_name: payment  
    environment:
      CART_HOST: cart
      CART_PORT: 8080
      USER_HOST: user
      USER_PORT: 8080
      AMQP_HOST: rabbitmq
      AMQP_USER: roboshop
      AMQP_PASS: roboshop123  
    depends_on:
    - cart
    - user
    - rabbitmq  

